name: flutter_vlc_player
description: A VLC-powered alternative to Flutter's video_player. Supports multiple players on one screen.
version: 3.0.6
homepage: https://github.com/solid-software/flutter_vlc_player

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cryptoutils: ^0.4.0

flutter:
  plugin:
    androidPackage: software.solid.fluttervlcplayer
    pluginClass: FlutterVlcPlayerPlugin