name: flutter_vlc_player
description: A VLC-powered alternative to Flutter's video_player. Supports multiple players on one screen.
version: 7.1.5
homepage: https://github.com/solid-software/flutter_vlc_player/

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.0"

flutter:
  plugin:
    platforms:
      android:
        package: software.solid.fluttervlcplayer
        pluginClass: FlutterVlcPlayerPlugin
      ios:
        pluginClass: FlutterVlcPlayerPlugin

dependencies:
  flutter:
    sdk: flutter
 
  meta: ^1.7.0
  flutter_vlc_player_platform_interface: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  pigeon: ^0.2.4
  plugin_platform_interface: ^2.0.1
