name: flutter_vlc_player_16kb
description: A VLC-powered alternative to Flutter's video_player. Supports multiple players on one screen.
version: 7.4.5
homepage: https://github.com/naylinndev/flutter_vlc_player_16kb/
repository: https://github.com/naylinndev/flutter_vlc_player_16kb

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.8.0 <4.0.0'

flutter:
  plugin:
    platforms:
      android:
        package: software.solid.fluttervlcplayer
        pluginClass: FlutterVlcPlayerPlugin
      ios:
        pluginClass: FlutterVlcPlayerPlugin

dependencies:
  flutter:
    sdk: flutter

  flutter_vlc_player_platform_interface: ^2.0.5
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  pigeon: ^26.0.1
  plugin_platform_interface: ^2.1.8
  solid_lints: ^0.3.1
