name: flutter_vlc_player
description: A VLC-powered alternative to Flutter's video_player. Supports multiple players on one screen.
version: 7.4.3
homepage: https://github.com/solid-software/flutter_vlc_player/

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

flutter:
  plugin:
    platforms:
      android:
        package: software.solid.fluttervlcplayer
        pluginClass: FlutterVlcPlayerPlugin
      ios:
        pluginClass: FlutterVlcPlayerPlugin

dependencies:
  flutter:
    sdk: flutter

  flutter_vlc_player_platform_interface: ^2.0.5
  meta: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  pigeon: ^0.2.4
  plugin_platform_interface: ^2.1.3
  solid_lints: ^0.2.3
