name: flutter_vlc_player_platform_interface
description: A common platform interface for the flutter vlc player plugin.
homepage: https://github.com/solid-software/flutter_vlc_player
version: 1.0.1

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.2.4
  plugin_platform_interface: ^1.0.3
  pedantic: ^1.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.3
