name: flutter_vlc_player_platform_interface
description: A common platform interface for the flutter vlc player plugin.
homepage: https://github.com/solid-software/flutter_vlc_player
version: 1.0.6

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  plugin_platform_interface: ^2.0.0
  pedantic: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.7
